Repository frontend-park-mail-ru/2022_1_devo4ki_na_d1skoteke, pull requests merged in 2022-03, with the labels that each got.

#6 signup login done for RK1
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/components/Auth/Auth.css
  public/components/Auth/Auth.js
  public/components/Auth/Auth.pug
  public/img/favicon.ico
  public/img/signup_login_logo.png
  public/index.css
  public/index.html
  public/index.js
  public/js/utils.js
  public/modules/ajax.js
  server.js
Labels: need small edits

#7 Tp 396 network module
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/components/LeftSideBar/LeftSideBar.css
  public/components/LeftSideBar/LeftSideBar.js
  public/components/LeftSideBar/LeftSideBar.pug
  public/components/NoteContent/NoteContent.css
  public/components/NoteContent/NoteContent.js
  public/components/NoteContent/NoteContent.pug
  public/index.html
  public/index.js
  public/store/ApiStore.js
  public/styles.css
  public/views/note.js
  server.js
  yarn.lock
Labels: need edits

#5 TP 070 templates and components for login signup
  .eslintignore
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/components/Auth/Auth.css
  public/components/Auth/Auth.js
  public/components/Auth/Auth.pug
  public/img/favicon.ico
  public/img/signup_login_logo.png
  public/index.css
  public/index.html
  public/index.js
  public/js/utils.js
  public/modules/ajax.js
  server.js
Labels: ready to main
